/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EscrowsRouteImport } from './routes/escrows'
import { Route as NewRouteImport } from './routes/new'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as SettlementsRouteImport } from './routes/settlements'
import { Route as VaultsRouteImport } from './routes/vaults'
import { Route as EscrowsIndexRouteImport } from './routes/escrows.index'
import { Route as EscrowsIdRouteImport } from './routes/escrows.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowsRoute = EscrowsRouteImport.update({
  id: '/escrows',
  path: '/escrows',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const SettlementsRoute = SettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsRoute = VaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowsIndexRoute = EscrowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EscrowsRoute,
} as any)
const EscrowsIdRoute = EscrowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EscrowsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/escrows': typeof EscrowsRouteWithChildren
  '/new': typeof NewRoute
  '/protocol': typeof ProtocolRoute
  '/settlements': typeof SettlementsRoute
  '/vaults': typeof VaultsRoute
  '/escrows/$id': typeof EscrowsIdRoute
  '/escrows/': typeof EscrowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/protocol': typeof ProtocolRoute
  '/settlements': typeof SettlementsRoute
  '/vaults': typeof VaultsRoute
  '/escrows/$id': typeof EscrowsIdRoute
  '/escrows': typeof EscrowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/escrows': typeof EscrowsRouteWithChildren
  '/new': typeof NewRoute
  '/protocol': typeof ProtocolRoute
  '/settlements': typeof SettlementsRoute
  '/vaults': typeof VaultsRoute
  '/escrows/$id': typeof EscrowsIdRoute
  '/escrows/': typeof EscrowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/escrows'
    | '/new'
    | '/protocol'
    | '/settlements'
    | '/vaults'
    | '/escrows/$id'
    | '/escrows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/protocol'
    | '/settlements'
    | '/vaults'
    | '/escrows/$id'
    | '/escrows'
  id:
    | '__root__'
    | '/'
    | '/escrows'
    | '/new'
    | '/protocol'
    | '/settlements'
    | '/vaults'
    | '/escrows/$id'
    | '/escrows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EscrowsRoute: typeof EscrowsRouteWithChildren
  NewRoute: typeof NewRoute
  ProtocolRoute: typeof ProtocolRoute
  SettlementsRoute: typeof SettlementsRoute
  VaultsRoute: typeof VaultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrows': {
      id: '/escrows'
      path: '/escrows'
      fullPath: '/escrows'
      preLoaderRoute: typeof EscrowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settlements': {
      id: '/settlements'
      path: '/settlements'
      fullPath: '/settlements'
      preLoaderRoute: typeof SettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults': {
      id: '/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof VaultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrows/': {
      id: '/escrows/'
      path: '/'
      fullPath: '/escrows/'
      preLoaderRoute: typeof EscrowsIndexRouteImport
      parentRoute: typeof EscrowsRoute
    }
    '/escrows/$id': {
      id: '/escrows/$id'
      path: '/$id'
      fullPath: '/escrows/$id'
      preLoaderRoute: typeof EscrowsIdRouteImport
      parentRoute: typeof EscrowsRoute
    }
  }
}

interface EscrowsRouteChildren {
  EscrowsIdRoute: typeof EscrowsIdRoute
  EscrowsIndexRoute: typeof EscrowsIndexRoute
}

const EscrowsRouteChildren: EscrowsRouteChildren = {
  EscrowsIdRoute: EscrowsIdRoute,
  EscrowsIndexRoute: EscrowsIndexRoute,
}

const EscrowsRouteWithChildren =
  EscrowsRoute._addFileChildren(EscrowsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EscrowsRoute: EscrowsRouteWithChildren,
  NewRoute: NewRoute,
  ProtocolRoute: ProtocolRoute,
  SettlementsRoute: SettlementsRoute,
  VaultsRoute: VaultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
